/*
 ISC License

 Copyright (c) 2025, Autonomous Vehicle Systems Lab, University of Colorado at Boulder

 Permission to use, copy, modify, and/or distribute this software for any
 purpose with or without fee is hereby granted, provided that the above
 copyright notice and this permission notice appear in all copies.

 THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

 */

using TMPro;
using UnityEngine;
/// <summary>
/// Sets up, draws, and updates a keep-out or keep-in cone
/// </summary>

public class DrawKeepOutInCone : MonoBehaviour {

	private bool coneViolation;
	private string fromBodyName; 
	private string toBodyName;
	public bool isKeepOut;
	private Color coneColor;
	private Vector3 coneOrigin = Vector3.zero; 
	private Vector3 coneNormal = Vector3.one;
	private float coneAngle;
	private float coneHeight;
	private string coneLabel;
	private bool autogeneratedName;
	private GameObject visibleCone;
	private GameObject invisibleCone;
	private GameObject toBodyObject;
	private GameObject myConeButton;
	private bool firstUpdate;
	private bool inSpriteMode;

	void FixedUpdate(){
		float toBodyDistance = GetScaledDistanceBetweenBodies ();
		invisibleCone.transform.localScale = new Vector3 (toBodyDistance, toBodyDistance, toBodyDistance);
		
		if (firstUpdate)
		{
			SetConeViolated (true);
			firstUpdate = false;
		}
	}
	public void InitializeKeepOutInCone(string fromBody, string toBody, bool keepOut, Color newColor, Vector3 origin, Vector3 normal, float angle, float height, string givenName= "autogeneratenameifblank", string effectorParentName = ""){
		fromBodyName = fromBody;
		toBodyName = toBody;
		coneColor = newColor;
		isKeepOut = keepOut;

		coneLabel = $"{fromBodyName} to {toBodyName}";
		coneAngle = angle;
		coneHeight = height;
		coneOrigin = origin; //in BSK CS
		coneNormal = normal; //in BSK CS
		autogeneratedName = false;
		if ((givenName == "autogeneratenameifblank") ||(autogeneratedName)||(givenName=="")){
			if (isKeepOut) {
				coneLabel = coneLabel + " Keep Out Cone";
			} else {
				coneLabel = coneLabel + " Keep In Cone";
			}
			autogeneratedName = true;

		} else {
			coneLabel = givenName;
			autogeneratedName = false;
		}
		//Create references to the visible cone and the invisible collider cone
		visibleCone = transform.GetChild(0).gameObject;
		invisibleCone = transform.GetChild(1).gameObject;

		//Create a reference to get the to body we're trying to keep outside or inside the cone
		toBodyObject=CelestialBodyStateUtilities.GetLineTargetGameObjectWithName(toBodyName, effectorParentName);


		transform.gameObject.name = coneLabel;
		Quaternion directionToPoint = Quaternion.LookRotation (new Vector3(normal.y, normal.z, -normal.x)); //Converted to Unity CS
		transform.localRotation = directionToPoint;
		transform.localPosition = new Vector3 (origin.y, origin.z, -origin.x); //Converted to Basilisk CS
		transform.localScale = new Vector3(Mathf.Tan(angle*Mathf.PI/180), Mathf.Tan(angle*Mathf.PI/180), 1);

		visibleCone.transform.localScale = new Vector3 (coneHeight, coneHeight, coneHeight);
		visibleCone.GetComponent<MeshRenderer> ().material.color = coneColor;


		float toBodyDistance = GetScaledDistanceBetweenBodies ();
		invisibleCone.transform.localScale = new Vector3 (toBodyDistance, toBodyDistance, toBodyDistance);
		invisibleCone.GetComponent<ConeTrigger> ().InitializeTrigger(toBodyObject,isKeepOut);
		if (!isKeepOut)
		{
			firstUpdate = true;
		}
	}

	private float GetScaledDistanceBetweenBodies(){
		return Vector3.Magnitude (toBodyObject.transform.position - transform.position);
	}
	public Color GetConeColor(){
		return coneColor;
	}

	public void SetConeColor(Color newColor){
		coneColor = newColor;
	}

	public string GetConeLabel(){
		return coneLabel;
	}

	public bool GetIsKeepOut(){
		return isKeepOut;
	}

	public Vector3 GetConeOrigin(){
		return coneOrigin;
	}
	public Vector3 GetConeNormal(){
		return coneNormal;
	}	
	public float GetConeAngle(){
		return coneAngle;
	}

	public float GetConeHeight(){
		return coneHeight;
	}

	public string GetFromBody(){
		return fromBodyName;
	}

	public string GetToBody(){
		return toBodyName;
	}

	public bool IsAutogeneratedName(){
		return autogeneratedName;
	}

	public void SetConeViolated(bool coneState){
		coneViolation = coneState;
		if (coneViolation) {
			myConeButton.GetComponentInChildren<TextMeshProUGUI> ().color = new Color(1,0,0,.5f);
			visibleCone.GetComponent<MeshRenderer> ().material.color = new Color(coneColor.r, coneColor.g, coneColor.b, 0.8f);
		} else {
			myConeButton.GetComponentInChildren<TextMeshProUGUI> ().color = new Color (0.39f, 1, 0.39f, 1);
			visibleCone.GetComponent<MeshRenderer> ().material.color = new Color(coneColor.r, coneColor.g, coneColor.b, 0.16f);
		}
	}

	public void SetMyConeButton(GameObject button){
		myConeButton = button;
		myConeButton.GetComponentInChildren<TextMeshProUGUI> ().color = new Color (0.39f, 1, 0.39f, 1);
	}
	
	/// <summary>
	/// This receives a BroadcastMessage from the parent Spacecraft when
	/// going into sprite mode. Don't delete. 
	/// </summary>
	/// <param name="spriteOn">True if attached spacecraft is in sprite mode</param>
	public void ConfigureHUDForSpriteMode(bool spriteOn)
	{
		visibleCone.SetActive(!spriteOn);
	}
}
